APP_ROOT=/home/eventos
BACKEND=$(APP_ROOT)/FastAPI_TCS
VENV=$(BACKEND)/venv

.PHONY: env backend gunicorn deploy

env:
	@echo "Creando $(BACKEND)/.env desde variables del sistema..."
	@cat <<EOF > $(BACKEND)/.env
SUPPORT_KEY=$$SUPPORT_KEY
SEAT_RESERVATION_TTL_MINUTES=$$SEAT_RESERVATION_TTL_MINUTES

CORS_ORIGINS=$$CORS_ORIGINS

WOMPI_API_URL=$$WOMPI_API_URL
WOMPI_PUBLIC_KEY=$$WOMPI_PUBLIC_KEY
WOMPI_PRIVATE_KEY=$$WOMPI_PRIVATE_KEY
WOMPI_SECRET_EVENT=$$WOMPI_SECRET_EVENT
WOMPI_SECRET_INTEGRITY=$$WOMPI_SECRET_INTEGRITY

PLACETOPAY_URL=$$PLACETOPAY_URL
PLACETOPAY_LOGIN=$$PLACETOPAY_LOGIN
PLACETOPAY_TRANKEY=$$PLACETOPAY_TRANKEY
PLACETOPAY_RETURN_URL=$$PLACETOPAY_RETURN_URL

MSSQL_DB=$$MSSQL_DB
MSSQL_STORAGE=$$MSSQL_STORAGE
MSSQL_HOST=$$MSSQL_HOST
MSSQL_PORT=$$MSSQL_PORT
MSSQL_USER=$$MSSQL_USER
MSSQL_PASSWORD=$$MSSQL_PASSWORD
MSSQL_DRIVER=$$MSSQL_DRIVER

SIESA_WSDL_URL=$$SIESA_WSDL_URL
SIESA_F_CIA=$$SIESA_F_CIA
SIESA_ID_SUCURSAL=$$SIESA_ID_SUCURSAL

MAIL_SERVER=$$MAIL_SERVER
MAIL_PORT=$$MAIL_PORT
MAIL_USE_TLS=$$MAIL_USE_TLS
MAIL_USE_SSL=$$MAIL_USE_SSL

MAIL_USERNAME_ATTENDEES=$$MAIL_USERNAME_ATTENDEES
MAIL_PASSWORD_ATTENDEES=$$MAIL_PASSWORD_ATTENDEES
COMPANY_LOGO_URL_ATTENDEES=$$COMPANY_LOGO_URL_ATTENDEES
COMPANY_LOGO_FILE_ATTENDEES=$$COMPANY_LOGO_FILE_ATTENDEES

MAIL_USERNAME_TICKETS=$$MAIL_USERNAME_TICKETS
MAIL_PASSWORD_TICKETS=$$MAIL_PASSWORD_TICKETS
COMPANY_LOGO_URL_TICKETS=$$COMPANY_LOGO_URL_TICKETS
COMPANY_LOGO_FILE_TICKETS=$$COMPANY_LOGO_FILE_TICKETS

LOG_LEVEL=$$LOG_LEVEL
EOF
	@echo "Backend .env creado correctamente"

backend: env
	cd $(BACKEND) && mkdir -p logs
	cd $(BACKEND) && uv sync

gunicorn:
	-pkill gunicorn
	sudo cp $(APP_ROOT)/gunicorn.service /etc/systemd/system/
	sudo systemctl daemon-reload
	sudo systemctl enable gunicorn
	sudo systemctl restart gunicorn

deploy: backend gunicorn
	@echo "Backend desplegado correctamente"