"""db dev

Revision ID: e0f424a2ada4
Revises: 
Create Date: 2026-04-13 11:03:26.847054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f424a2ada4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('staff_price', sa.Integer(), nullable=False),
    sa.Column('combo_price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nit_type', sa.String(length=10), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name_1', sa.String(length=80), nullable=False),
    sa.Column('last_name_2', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cell_phone', sa.String(length=20), nullable=False),
    sa.Column('siesa_id', sa.String(length=20), nullable=False),
    sa.Column('person_source', sa.String(length=20), nullable=False, comment='EMPLOYEE | STUDENT | FAMILY'),
    sa.Column('family_id', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('nit_type', sa.String(length=10), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name_1', sa.String(length=80), nullable=False),
    sa.Column('last_name_2', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cell_phone', sa.String(length=20), nullable=False),
    sa.Column('person_source', sa.String(length=20), nullable=False, comment='EMPLOYEE | STUDENT | FAMILY'),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('shirt_size', sa.String(length=10), nullable=False, comment='8|12|14|16|XS|S|M|L|XL'),
    sa.Column('age_range', sa.String(length=20), nullable=False, comment='5-10|11-17|18-25|...'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('eps', sa.String(length=80), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('medical_info', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('seats', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('wompi_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('siesa_invoice_number', sa.String(length=50), nullable=True),
    sa.Column('siesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('siesa_error', sa.Text(), nullable=True),
    sa.Column('siesa_response', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('placetopay_request_id', sa.String(length=100), nullable=True),
    sa.Column('placetopay_session_url', sa.String(length=500), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('order_tickets')
    op.drop_table('order_attendees')
    op.drop_table('orders')
    op.drop_table('events')
    # ### end Alembic commands ###
